import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { BarChart3, TrendingUp, Users, DollarSign, Zap } from 'lucide-react';

const DashboardContainer = styled.div`
  padding: 1.5rem;
`;

const DashboardHeader = styled.div`
  margin-bottom: 2rem;
`;

const DashboardTitle = styled.h1`
  font-size: 1.75rem;
  font-weight: 700;
  color: #1e293b;
  margin: 0 0 0.5rem 0;
`;

const DashboardSubtitle = styled.p`
  color: #64748b;
  margin: 0;
`;

const StatsGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1.5rem;
  margin-bottom: 2rem;
`;

const StatCard = styled.div`
  background: white;
  border-radius: 1rem;
  padding: 1.5rem;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
  border: 1px solid #e2e8f0;
  display: flex;
  flex-direction: column;
`;

const StatHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
`;

const StatIcon = styled.div`
  width: 3rem;
  height: 3rem;
  border-radius: 0.75rem;
  display: flex;
  align-items: center;
  justify-content: center;
  background: ${props => props.color || '#3b82f6'};
  color: white;
`;

const StatTitle = styled.h3`
  font-size: 0.875rem;
  font-weight: 500;
  color: #64748b;
  margin: 0;
`;

const StatValue = styled.div`
  font-size: 1.75rem;
  font-weight: 700;
  color: #1e293b;
  margin-bottom: 0.25rem;
`;

const StatChange = styled.div`
  font-size: 0.875rem;
  color: ${props => props.positive ? '#10b981' : '#ef4444'};
  display: flex;
  align-items: center;
  gap: 0.25rem;
`;

const AIDashboard = () => {
  // Sample stat cards
  const statCards = [
    {
      title: "Total Revenue",
      value: "$45,231.89",
      change: "+20.1%",
      icon: <DollarSign size={20} />,
      color: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
      changePositive: true
    },
    {
      title: "Active Users",
      value: "12,234",
      change: "+15.3%",
      icon: <Users size={20} />,
      color: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
      changePositive: true
    },
    {
      title: "Conversion Rate",
      value: "8.2%",
      change: "+2.1%",
      icon: <TrendingUp size={20} />,
      color: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
      changePositive: true
    },
    {
      title: "Avg. Response Time",
      value: "1.2s",
      change: "-12.4%",
      icon: <Zap size={20} />,
      color: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
      changePositive: true
    }
  ];

  return (
    <DashboardContainer>
      <DashboardHeader>
        <DashboardTitle>AI-Powered Analytics Dashboard</DashboardTitle>
        <DashboardSubtitle>Real-time insights generated by AI</DashboardSubtitle>
      </DashboardHeader>
      
      <StatsGrid>
        {statCards.map((stat, index) => (
          <StatCard key={index}>
            <StatHeader>
              <StatTitle>{stat.title}</StatTitle>
              <StatIcon style={{ background: stat.color }}>
                {stat.icon}
              </StatIcon>
            </StatHeader>
            <StatValue>{stat.value}</StatValue>
            <StatChange positive={stat.changePositive}>
              {stat.change}
            </StatChange>
          </StatCard>
        ))}
      </StatsGrid>
      
      {/* Removed chart components */}
    </DashboardContainer>
  );
};

export default AIDashboard;